home_assistant:
  url: ''
  token: ''
ember:
  host: 0.0.0.0
  port: 9000
  root_identifier: homeassistant
web:
  host: 0.0.0.0
  port: 8090
write_control:
  cooldown_ms: 400
  debounce_ms: 150
advanced:
  enable_all_entities: false
exports: []
